### ISSUE TITLE
Refresh Profile from Server in Mavensmate, not refreshing correct data

### ISSUE THREAD

**Issue by DawidN** [joeferraro/MavensMate#390] opened 2015-01-08 05:28 UTC
When I right click on some metadata in Mavensmate, and I say "Refresh from server", all the metadata dissapears and only header level remains. I am testing with refreshing a profile. If I refresh at the Project level, it refreshes correctly.
![1](https://cloud.githubusercontent.com/assets/8489880/5658285/015c046c-974b-11e4-85d4-29135b3171b2.jpg)

**Comment by TehNrd** [comment] 2015-04-24 13:26
Unfortunately I have little of value to add other than I am also seeing this as well.

**Comment by joeferraro** [comment] 2015-04-24 13:29
When refreshing a single profile, MavensMate sends that profile up for retrieval by itself. In order to provide context to the retrieve, the Metadata API requires all other project metadata to be included in the retrieval. The enhancement would be for MavensMate to detect that a profile is being refreshed by itself and proactively include all other project metadata in the retrieve, however, this approach isn't always perfect (there's a chance a user is trying to retrieve a profile by itself). The workaround for now is to clean the project, which will retrieve the entire project based on package.xml.

**Comment by TehNrd** [comment] 2015-04-24 13:29
Looks like this may be the same issue @joeferraro mentioned here: https://github.com/joeferraro/MavensMate/issues/193#issuecomment-39869574

If you refresh from the src directory you should get the changes....but you will also get a ton of other modified files.

**Comment by joeferraro** [comment] 2015-04-24 13:30
duplicate of #193 thanks @TehNrd

**Closed by joeferraro** 2015-04-24 13:30 UTC
