### ISSUE TITLE
Not able to install MavensMate-Atom. First time user to Atom.

### ISSUE THREAD

**Issue by DhDeveloper** [joeferraro/MavensMate#940] opened 2017-03-03 16:11 UTC
* **MavensMate Desktop Version**: v0.0.11-beta.7

* **Editor**:Atom

* **MavensMate Plugin Version**:1.0.10

* **Platform/Version**:Windows 7 64-bit

* **Proxy Details**:Maybe

* **Salesforce API Version**:39

* **Salesforce Server**:cs14

npm WARN deprecated node-uuid@1.4.1: use uuid module instead
npm ERR! git clone C:\Users\<username>\.atom\.apm\_git-remotes\git-https-gi
thub-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96
-f622d8c9 C:\Users\<username>\AppData\Local\Temp\npm-5088-a92f3368\git-cache-e
9db049c\e81b4b808359e2def9eeeabfdee69c2989e1fe96: Cloning into 'C:\Users\MURALI~
1.DHA\AppData\Local\Temp\npm-5088-a92f3368\git-cache-e9db049c\e81b4b808359e2def9
eeeabfdee69c2989e1fe96'...
npm ERR! git clone C:\Users\<username>\.atom\.apm\_git-remotes\git-https-gi
thub-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96
-f622d8c9 C:\Users\<username>\AppData\Local\Temp\npm-5088-a92f3368\git-cache-e
9db049c\e81b4b808359e2def9eeeabfdee69c2989e1fe96: error: cannot spawn sh: No suc
h file or directory
npm ERR! git clone C:\Users\<username>\.atom\.apm\_git-remotes\git-https-gi
thub-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96
-f622d8c9 C:\Users\<username>\AppData\Local\Temp\npm-5088-a92f3368\git-cache-e
9db049c\e81b4b808359e2def9eeeabfdee69c2989e1fe96: fatal: unable to fork
npm ERR! git clone C:\Users\<username>\.atom\.apm\_git-remotes\git-https-gi
thub-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96
-f622d8c9 C:\Users\<username>\AppData\Local\Temp\npm-5088-a92f3368\git-cache-e
9db049c\e81b4b808359e2def9eeeabfdee69c2989e1fe96:
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\<username>\\AppData\\Local\\atom\\app-1.14.4\\res
ources\\app\\apm\\bin\\node.exe" "C:\\Users\\<username>\\AppData\\Local\\at
om\\app-1.14.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--glob
alconfig" "C:\\Users\\<username>\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\
Users\\<username>\\.atom\\.apmrc" "install" "C:\\Users\\<username>\\AppDa
ta\\Local\\Temp\\d-11723-6700-14re1mn\\package.tgz" "--runtime=electron" "--targ
et=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone C:\Users\murali.dharna
la\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e
81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9 C:\Users\<username>\AppData\L
ocal\Temp\npm-5088-a92f3368\git-cache-e9db049c\e81b4b808359e2def9eeeabfdee69c298
9e1fe96
npm ERR! Cloning into 'C:\Users\<username>\AppData\Local\Temp\npm-5088-a92f336
8\git-cache-e9db049c\e81b4b808359e2def9eeeabfdee69c2989e1fe96'...
npm ERR! error: cannot spawn sh: No such file or directory
npm ERR! fatal: unable to fork
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\<username>\AppData\Local\Temp\apm-install-dir-11723-6700

Getting this issue.. Help me to resolve

**Comment by Code-for-Children** [comment] 2017-07-25 14:02
Same error, environment: 
`apm`  1.18.1
`npm`  3.10.10
`node` 6.9.5 x64
`python`
`git` 2.13.3.windows.1
`visual studio`

**Comment by CodeMonkeyG** [comment] 2017-08-03 20:41
I've hit this same issue and after some investigation, the URL for the repo that NPM is trying to clone from during the install process no longer exists.
https://github.com/Benvie/harmony-collections.git/

[The NPM page still does though,](https://www.npmjs.com/package/harmony-collections) and `npm install harmony-collections` also works.

**Comment by steals** [comment] 2017-08-05 06:35
@Code-for-Children @CodeMonkeyG check the solution here https://github.com/joeferraro/MavensMate/issues/907#issuecomment-277942432

@kidtsunami can you mark this issue as duplicate of #907

**Comment by CodeMonkeyG** [comment] 2017-08-07 03:56
@steals: Worked for me, thank you.

**Comment by kidtsunami** [comment] 2017-08-07 18:17
Duplicate of #890

**Closed by kidtsunami** 2017-08-07 18:17 UTC
