### ISSUE TITLE
Resource Not Found. Response content: [{u'errorCode': u'NOT_FOUND', u'message': u'The requested resource does not exist'}]

### ISSUE THREAD

**Issue by sdhaliwal16** [joeferraro/MavensMate#685] opened 2016-06-30 20:44 UTC
I am not able to create a new MavenMate Project. The following error is being displayed: 

Resource Not Found. Response content: [{u'errorCode': u'NOT_FOUND', u'message': u'The requested resource does not exist'}]

**Comment by pbattisson** [comment] 2016-07-01 09:29
Closing duplicate of #684

**Closed by pbattisson** 2016-07-01 09:29 UTC
