### ISSUE TITLE
Authentication failed for 'https://github.com/Benvie/harmony-collections.git/'

### ISSUE THREAD

**Issue by abhigoel** [joeferraro/MavensMate#998] opened 2017-07-26 08:07 UTC
MavensMate Desktop Version: v.0.0.11-beta.7
Editor: Atom
MavensMate Plugin Version: 1.0.10
Platform/Version: Windows 10
Proxy Details: No
Salesforce API Version: 39.0
Salesforce Server: Not applicable

npm WARN deprecated node-uuid@1.4.1: Use uuid module instead
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)
npm WARN addRemoteGit  git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 resetting remote C:\Users\XXXX\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\XXXX\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\XXXX\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: Cloning into bare repository 'C:\Users\XXXX\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9'...
npm ERR! git clone --template=C:\Users\XXXX\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\XXXX\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: remote: Invalid username or password.
npm ERR! git clone --template=C:\Users\XXXX\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\XXXX\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: fatal: Authentication failed for 'https://github.com/Benvie/harmony-collections.git/'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Users\\XXXX\\AppData\\Local\\atom\\app-1.18.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\XXXX\\AppData\\Local\\atom\\app-1.18.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\XXXX\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\XXXX\\.atom\\.apmrc" "install" "C:\\Users\\XXXX\\AppData\\Local\\Temp\\d-117626-956-1jfbhuy.9got70t3xr\\package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\XXXX\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\XXXX\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9
npm ERR! Cloning into bare repository 'C:\Users\XXXX\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9'...
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/Benvie/harmony-collections.git/'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:

**Comment by andresj** [comment] 2017-07-28 06:08
Having similar error here. When trying to install atom plugin on my Ubuntu I receive this output:

npm WARN deprecated node-uuid@1.4.1: Use uuid module instead
npm ERR! git clone --template=/home/XXXX/.atom/.apm/_git-remotes/_templates --mirror https://github.com/Benvie/harmony-collections.git /home/XXXX/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: Cloning into bare repository '/home/XXXX/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9'...
npm ERR! git clone --template=/home/XXXX/.atom/.apm/_git-remotes/_templates --mirror https://github.com/Benvie/harmony-collections.git /home/XXXX/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: remote: Invalid username or password.
npm ERR! git clone --template=/home/XXXX/.atom/.apm/_git-remotes/_templates --mirror https://github.com/Benvie/harmony-collections.git /home/XXXX/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: fatal: Authentication failed for 'https://github.com/Benvie/harmony-collections.git/'
npm ERR! Linux 4.6.7-040607-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/XXXX/.atom/.apm/.apmrc" "--userconfig" "/home/XXXX/.atom/.apmrc" "install" "/tmp/d-117628-4254-c2kl9t.g4bvhg2e29/package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/XXXX/.atom/.apm/_git-remotes/_templates --mirror https://github.com/Benvie/harmony-collections.git /home/XXXX/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9
npm ERR! Cloning into bare repository '/home/XXXX/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9'...
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/Benvie/harmony-collections.git/'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-117628-4254-tsfcro.kzrr4quxr/npm-debug.log

**Comment by karlkras** [comment] 2017-07-30 17:15
+1  please address.

**Comment by helloandie** [comment] 2017-07-31 18:04
+1 same thing here.

**Comment by dyehya** [comment] 2017-08-02 23:22
+1 Same issue log below. Debug can be attached if needed.
```
npm WARN deprecated node-uuid@1.4.1: Use uuid module instead
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)
npm WARN addRemoteGit  git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 resetting remote C:\Users\Danny\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\Danny\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\Danny\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: Cloning into bare repository 'C:\Users\Danny\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9'...
npm ERR! git clone --template=C:\Users\Danny\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\Danny\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: github --credentials get: github: command not found
npm ERR! git clone --template=C:\Users\Danny\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\Danny\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: github --credentials erase: github: command not found
npm ERR! git clone --template=C:\Users\Danny\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\Danny\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: remote: Invalid username or password.
npm ERR! git clone --template=C:\Users\Danny\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\Danny\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: fatal: Authentication failed for 'https://github.com/Benvie/harmony-collections.git/'
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Users\\Danny\\AppData\\Local\\atom\\app-1.18.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Danny\\AppData\\Local\\atom\\app-1.18.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Danny\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Danny\\.atom\\.apmrc" "install" "C:\\Users\\Danny\\AppData\\Local\\Temp\\d-11772-33164-11axhon.qoxwmw8kt9\\package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Danny\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\Danny\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9
npm ERR! Cloning into bare repository 'C:\Users\Danny\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9'...
npm ERR! github --credentials get: github: command not found
npm ERR! github --credentials erase: github: command not found
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/Benvie/harmony-collections.git/'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Danny\AppData\Local\Temp\apm-install-dir-11772-33164-s7igye.bjhhq6w29\npm-debug.log
```

**Comment by karlkras** [comment] 2017-08-03 00:36
Someone take their toys and go home?

**Comment by kidtsunami** [comment] 2017-08-03 05:37
Just out of curiosity, what is your MavensMate setting for MAVENSMATE TEMPLATE SOURCE (MM_TEMPLATE_SOURCE)?

**Comment by andresj** [comment] 2017-08-03 06:32
My MM_TEMPLATE_LOCATION is set to remote. This is the value of my MM_TEMPLATE_SOURCE:
joeferraro/MavensMate-Templates/master

**Comment by kidtsunami** [comment] 2017-08-03 06:55
And this is only happening to Atom folks? No VSCode or Sublime plugin users here?

**Comment by andresj** [comment] 2017-08-03 07:05
Only happening in Atom to me. Yesterday, I installed MM for VSCode and had no issues

**Comment by chrsnchrs** [comment] 2017-08-04 18:49
Having a similar issue trying to install through atom on WIN7 machine.  Now it looks like the repository is gone :

````
npm WARN deprecated node-uuid@1.4.1: Use uuid module instead
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)
npm WARN addRemoteGit  git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 resetting remote C:\Users\christianc\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\christianc\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\christianc\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: Cloning into bare repository 'C:\Users\christianc\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9'...
npm ERR! git clone --template=C:\Users\christianc\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\christianc\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: remote: Repository not found.
npm ERR! git clone --template=C:\Users\christianc\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\christianc\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: fatal: repository 'https://github.com/Benvie/harmony-collections.git/' not found
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\christianc\\AppData\\Local\\atom\\app-1.18.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\christianc\\AppData\\Local\\atom\\app-1.18.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\christianc\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\christianc\\.atom\\.apmrc" "install" "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp\\d-11774-10176-bwmaec.f4we3fpqfr\\package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style" "--msvs_version=2013"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\christianc\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\christianc\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9
npm ERR! Cloning into bare repository 'C:\Users\christianc\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9'...
npm ERR! remote: Repository not found.
npm ERR! fatal: repository 'https://github.com/Benvie/harmony-collections.git/' not found
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\CHRIST~1\AppData\Local\Temp\apm-install-dir-11774-10176-1934jrv.dyhwwxw29\npm-debug.log
```
`

**Comment by kidtsunami** [comment] 2017-08-04 20:36
MM For VS Code dev here, I've checked and this definitely looks borked in Atom. I haven't cracked that project open in awhile, so we may not have a fix for you soon...

**Comment by steals** [comment] 2017-08-05 06:36
Hi folks, please check the solution here https://github.com/joeferraro/MavensMate/issues/907#issuecomment-277942432

@kidtsunami can you mark this issue as duplicate of #907

**Comment by kidtsunami** [comment] 2017-08-07 18:18
of course @steals 

Duplicate of #890

**Closed by kidtsunami** 2017-08-07 18:18 UTC

**Comment by dyehya** [comment] 2017-08-07 18:33
Thanks @steals 
For anyone that isn't that technical trying to get it work:
Make sure Atom is closed before beginning.
1. Download the zip https://github.com/joeferraro/MavensMate-Atom of the source code [https://github.com/joeferraro/MavensMate-Atom/archive/master.zip](url)
2. Extract to your packages directory  (~/.atom/packages) or (C:\Users\\**Username**\\.atom\packages)
2b. Rename ~/.atom/packages/MavensMate-Atom-master to ~/.atom/packages/MavensMate-Atom or C:\Users\\**Username**\\.atom\packages\MavensMate-Atom-master to C:\Users\\**Username**\\.atom\packages\MavensMate-Atom
3. Install Node.JS if you haven't already [https://nodejs.org/](url)
4. From command-line navigate to the folder WITHIN the packages folder that you extracted. (~/.atom/packages/MavensMate-Atom) or (C:\Users\\**Username**\\.atom\packages\MavensMate-Atom)
5. From command line run: **npm install**
Note: Do **not** do npm install MavensMate-Atom as this will not work.
6. Start Atom error free :)
