### ISSUE TITLE
Sharing Rules

### ISSUE THREAD

**Issue by jarenyach** [joeferraro/MavensMate#404] opened 2015-02-11 20:43 UTC
When I subscribe to caseSharing rules as a metadata option, the folder does not get created locally.  The option also doesn't exist in the package.xml.

I am using mavensmate v4.0.2

**Comment by ralphcallaway** [comment] 2015-12-13 22:38
working with latest version (v7)
- added a case sharing rule in a dev org
- added sharing rules to dev project subscription
- refreshed index
- added case sharing rule
- refreshed project
- sharing rule pulled down locally into sharingRules folder

closing this out since i can't reproduce in the latest version

@jarenyach if this is still occuring for you please re-open and update your issue according to the guidelines thanks! https://github.com/joeferraro/MavensMate/blob/master/CONTRIBUTING.md

**Closed by ralphcallaway** 2015-12-13 22:38 UTC
