### ISSUE TITLE
Asking for confirmation when refreshing metadata

### ISSUE THREAD

**Issue by fricco** [joeferraro/MavensMate#533] opened 2015-09-30 15:57 UTC
After latest update from MavensMate, now anytime I do a refresh from Sublime Text, Windows is asking me to confirm that I want to replace the unpackaged folder. Is there a way to avoid this?

**Comment by joeferraro** [comment] 2015-09-30 16:29
duplicate of https://github.com/joeferraro/MavensMate-SublimeText/issues/671

**Closed by joeferraro** 2015-09-30 16:29 UTC
