### ISSUE TITLE
JS error when trying to create new Salesforce Project from Sublime Text

### ISSUE THREAD

**Issue by mpassovoy** [joeferraro/MavensMate#580] opened 2015-10-09 16:17 UTC
MM for Sublime v6, MM-app 0.0.10-beta2

When trying to use the MavensMate drop-down within Sublime, I get the attached error over the MM-app.

It looks like when I try to create a new project straight from the MM-app it works fine.

![mm-app js error](https://cloud.githubusercontent.com/assets/5439640/10399237/455299c2-6e66-11e5-9334-ca5dc00b13a6.png)

**Comment by pbattisson** [comment] 2015-10-19 13:32
Hey

This is happening because the port that the Sublime plugin is trying to use to contact the mm-app is already in use. Can you check you do not have multiple instances of the mm-app running? 

It would be super helpful if you could also post all the details needed at the contributing guide https://github.com/joeferraro/MavensMate/blob/master/CONTRIBUTING.md so we can try to reproduce and dig deeper.

Thanks

Paul

**Comment by ralphcallaway** [comment] 2015-12-11 03:09
the mavensmate app isn't need for version 6, but is for version 7 of the st3 plugin, when you open the mavensmate app it's using the same port the st3 local version will use

for now you can just not open the mavensmate app

closing this out for now, but re-open if you're still having issues

**Closed by ralphcallaway** 2015-12-11 03:09 UTC
