### ISSUE TITLE
Metadata not shown in the application

### ISSUE THREAD

**Issue by fracarma** [joeferraro/MavensMate#715] opened 2016-09-14 08:33 UTC
* **MavensMate Version**: 0.0.11-beta2

* **Editor**: Sublime Text 3

* **Platform/Version**: Windows 7 64-bit

* **Salesforce Server**: cs82

Updating the project from MM app. The new classes on the server (created by another user) that were not previously present on project are correctly downloaded. I can see them in Sublime Side bar:

![sublimemavensbug1](https://cloud.githubusercontent.com/assets/12348998/18505102/f2d9ce6a-7a65-11e6-8c80-8171da3dc2a1.PNG)

But they are not in the Project Metadata on the app!

![sublimemavensbug2](https://cloud.githubusercontent.com/assets/12348998/18505156/42a150e4-7a66-11e6-9ade-a2625c73611f.PNG)

So I can't select them for deployment. Also by *searching* I can't find them.

In the app, if I try to run the new test class, it is there:

![sublimemavensbug3](https://cloud.githubusercontent.com/assets/12348998/18505198/76c3145c-7a66-11e6-8462-943bb5007629.PNG)

Here there is my project package:

![sublimemavensbug4](https://cloud.githubusercontent.com/assets/12348998/18505211/87d1786a-7a66-11e6-9db1-1bc5adc5896f.PNG)

**Comment by fracarma** [comment] 2016-09-14 08:43
Ok, I found **why** the metadata are not displayed on the app. **config/.org_metadata** is not updated when the project is updated.

**Comment by joeferraro** [comment] 2016-09-14 12:14
Thanks for the report. When in doubt clean your project or, from within the
UI, update the metadata index (found on Edit Project screen).

**Comment by joeferraro** [comment] 2016-09-15 19:07
Closing as this is by design at the moment. Follow this PR for enhancement discussion: https://github.com/joeferraro/MavensMate/pull/718

**Closed by joeferraro** 2016-09-15 19:07 UTC
